//! Autonomous module builder for self-extending platform capabilities.

/// Category of generated module.
#[derive(Debug, Clone, PartialEq)]
pub enum ModuleCategory {
    /// A security tool or capability.
    SecurityTool,
    /// An analysis or detection engine.
    AnalysisEngine,
    /// A data pipeline or processing module.
    DataPipeline,
    /// An adapter to an external integration.
    IntegrationAdapter,
    /// A reporting or output formatter.
    ReportGenerator,
}

/// Specification for a new module to be generated.
#[derive(Debug, Clone)]
pub struct ModuleSpec {
    /// Name of the module (must be a valid Rust identifier).
    pub name: String,
    /// Category of the module.
    pub category: ModuleCategory,
    /// Human-readable description of the module's purpose.
    pub description: String,
    /// Rust traits the module's primary struct must implement.
    pub required_traits: Vec<String>,
}

/// A template used as the basis for generating new modules.
#[derive(Debug, Clone)]
pub struct ModuleTemplate {
    /// Name of the template.
    pub name: String,
    /// Category this template targets.
    pub category: ModuleCategory,
    /// Skeleton Rust source code for the module.
    pub skeleton_code: String,
    /// Traits required by modules using this template.
    pub required_traits: Vec<String>,
    /// Template code for module unit tests.
    pub test_template: String,
}

/// A module that has been generated by the autonomous builder.
#[derive(Debug, Clone)]
pub struct GeneratedModule {
    /// Module name.
    pub name: String,
    /// Category.
    pub category: ModuleCategory,
    /// Generated Rust source code.
    pub source_code: String,
    /// Generated test code.
    pub test_code: String,
    /// Whether the module passed the quality gate.
    pub quality_passed: bool,
}

/// Quality gate configuration for generated modules.
#[derive(Debug, Clone)]
pub struct QualityGate {
    /// Whether the module must include at least one unit test.
    pub require_tests: bool,
    /// Whether all public items must have doc comments.
    pub require_docs: bool,
    /// Minimum number of public functions.
    pub min_public_functions: usize,
}

impl Default for QualityGate {
    fn default() -> Self {
        Self {
            require_tests: true,
            require_docs: true,
            min_public_functions: 1,
        }
    }
}

/// Quality gate check result.
#[derive(Debug, Clone)]
pub struct QualityGateResult {
    /// Whether the module passed all checks.
    pub passed: bool,
    /// List of issues found (empty if passed).
    pub issues: Vec<String>,
}

/// Autonomous module builder that can generate and validate new Rust modules.
#[derive(Debug, Clone)]
pub struct AutonomousBuilder {
    /// Available module templates.
    pub templates: Vec<ModuleTemplate>,
    /// Modules generated in this session.
    pub generated_modules: Vec<GeneratedModule>,
    /// Quality gate configuration.
    pub quality_gate: QualityGate,
}

impl AutonomousBuilder {
    /// Create a new builder with default templates and quality gate.
    pub fn new() -> Self {
        Self {
            templates: default_templates(),
            generated_modules: Vec::new(),
            quality_gate: QualityGate::default(),
        }
    }

    /// Generate a new module from the given specification.
    pub fn generate_module(&mut self, spec: &ModuleSpec) -> GeneratedModule {
        let template = self
            .templates
            .iter()
            .find(|t| t.category == spec.category)
            .cloned()
            .unwrap_or_else(|| default_template_for_category(&spec.category));

        let source_code = render_skeleton(&template.skeleton_code, spec);
        let test_code = render_test_skeleton(&template.test_template, spec);

        let mut module = GeneratedModule {
            name: spec.name.clone(),
            category: spec.category.clone(),
            source_code,
            test_code,
            quality_passed: false,
        };

        let gate_result = self.run_quality_gate(&module);
        module.quality_passed = gate_result.passed;
        self.generated_modules.push(module.clone());
        module
    }

    /// Validate a generated module against the quality gate.
    pub fn validate_module(&self, module: &GeneratedModule) -> QualityGateResult {
        self.run_quality_gate(module)
    }

    /// Integrate a validated module by recording it as available.
    ///
    /// Returns `Err` if the module has not passed the quality gate.
    pub fn integrate_module(&mut self, module: GeneratedModule) -> Result<(), String> {
        if !module.quality_passed {
            return Err(format!(
                "Module '{}' has not passed the quality gate and cannot be integrated.",
                module.name
            ));
        }
        if !self
            .generated_modules
            .iter()
            .any(|m| m.name == module.name)
        {
            self.generated_modules.push(module);
        }
        Ok(())
    }

    /// Run quality gate checks against a generated module.
    pub fn run_quality_gate(&self, module: &GeneratedModule) -> QualityGateResult {
        let mut issues = Vec::new();

        if self.quality_gate.require_tests && module.test_code.is_empty() {
            issues.push("Module has no test code.".to_string());
        }

        if self.quality_gate.require_docs
            && !module
                .source_code
                .lines()
                .any(|l| l.trim_start().starts_with("///"))
        {
            issues.push("Module has no doc comments on public items.".to_string());
        }

        let fn_count = module.source_code.matches("pub fn ").count();
        if fn_count < self.quality_gate.min_public_functions {
            issues.push(format!(
                "Module has only {fn_count} public function(s); minimum is {}.",
                self.quality_gate.min_public_functions
            ));
        }

        QualityGateResult {
            passed: issues.is_empty(),
            issues,
        }
    }

    /// Propose a capability extension based on gaps in the currently generated modules.
    pub fn propose_capability_extension(&self) -> Vec<String> {
        let categories_present: std::collections::HashSet<String> = self
            .generated_modules
            .iter()
            .map(|m| format!("{:?}", m.category))
            .collect();

        let all_categories = [
            "SecurityTool",
            "AnalysisEngine",
            "DataPipeline",
            "IntegrationAdapter",
            "ReportGenerator",
        ];

        all_categories
            .iter()
            .filter(|c| !categories_present.contains(**c))
            .map(|c| format!("Propose adding a {c} module to fill capability gap."))
            .collect()
    }
}

impl Default for AutonomousBuilder {
    fn default() -> Self {
        Self::new()
    }
}

/// Render the skeleton code by substituting the module name.
fn render_skeleton(skeleton: &str, spec: &ModuleSpec) -> String {
    skeleton
        .replace("{name}", &spec.name)
        .replace("{description}", &spec.description)
}

/// Render the test skeleton by substituting the module name.
fn render_test_skeleton(template: &str, spec: &ModuleSpec) -> String {
    template.replace("{name}", &spec.name)
}

/// Return a default template for the given module category.
fn default_template_for_category(category: &ModuleCategory) -> ModuleTemplate {
    ModuleTemplate {
        name: format!("{:?} Default", category),
        category: category.clone(),
        skeleton_code: format!(
            "//! {description} for the `{{name}}` module.\n\n\
             /// Primary struct for the {{name}} module.\n\
             #[derive(Debug, Clone)]\npub struct {{name}}Engine {{}}\n\n\
             impl {{name}}Engine {{\n    /// Create a new instance.\n    pub fn new() -> Self {{ Self {{}} }}\n}}\n",
            description = format!("{category:?}")
        ),
        required_traits: vec!["Debug".to_string(), "Clone".to_string()],
        test_template: "#[cfg(test)]\nmod tests {\n    use super::*;\n\n    #[test]\n    fn test_{name}_new() {\n        let engine = {name}Engine::new();\n        let _ = format!(\"{:?}\", engine);\n    }\n}\n".to_string(),
    }
}

/// Build the default set of module templates.
fn default_templates() -> Vec<ModuleTemplate> {
    [
        ModuleCategory::SecurityTool,
        ModuleCategory::AnalysisEngine,
        ModuleCategory::DataPipeline,
        ModuleCategory::IntegrationAdapter,
        ModuleCategory::ReportGenerator,
    ]
    .iter()
    .map(default_template_for_category)
    .collect()
}
