//! Async cross-module event bus for real-time communication between security engines.
//!
//! Allows James security modules to notify each other of discoveries, enabling
//! coordinated purple-team operations and autonomous response workflows.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use tokio::sync::broadcast;

/// Types of security events that can be published on the bus.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EventType {
    /// A vulnerability was discovered by any module.
    VulnDiscovered,
    /// An exploit blueprint was generated by the exploit engine.
    ExploitGenerated,
    /// A detection rule triggered during blue team analysis.
    DetectionTriggered,
    /// New threat intelligence was ingested.
    ThreatIntelUpdate,
    /// An APT emulation campaign advanced to a new phase.
    AptPhaseAdvanced,
    /// An anomaly was detected by blockchain security analysis.
    BlockchainAnomaly,
    /// The meta-agent proposed a new capability extension.
    ExtensionProposed,
    /// A pentest phase completed.
    PentestPhaseComplete,
}

/// A vulnerability finding shared across modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Finding {
    /// Unique identifier for this finding.
    pub id: String,
    /// Short title.
    pub title: String,
    /// Severity string (e.g. "High", "Critical").
    pub severity: String,
    /// Description of the vulnerability.
    pub description: String,
    /// Source module that produced this finding.
    pub source_module: String,
    /// Target or component affected.
    pub affected_target: String,
}

/// An exploit blueprint produced by the exploit engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExploitBlueprint {
    /// Vulnerability this exploit targets.
    pub vuln_id: String,
    /// CVE identifier if known.
    pub cve_id: Option<String>,
    /// Exploit type (e.g. "RCE", "LPE", "SQLi").
    pub exploit_type: String,
    /// Reliability score 0–100.
    pub reliability: u8,
    /// Recommended payloads or techniques.
    pub techniques: Vec<String>,
}

/// A detection alert raised by the blue team engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DetectionAlert {
    /// Rule identifier that fired.
    pub rule_id: String,
    /// Rule name.
    pub rule_name: String,
    /// Technique ID (MITRE ATT&CK) that was detected.
    pub technique_id: String,
    /// Whether the detection was a true positive (if known).
    pub true_positive: Option<bool>,
}

/// A threat intelligence indicator.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThreatIndicator {
    /// Indicator value (IP, hash, domain, etc.).
    pub value: String,
    /// Indicator type.
    pub indicator_type: String,
    /// Threat group or campaign associated.
    pub attribution: Option<String>,
    /// Confidence 0–100.
    pub confidence: u8,
}

/// A blockchain security anomaly.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlockchainAlert {
    /// Contract address or protocol name.
    pub target: String,
    /// Type of anomaly (e.g. "reentrancy", "MEV", "bridge_drain").
    pub anomaly_type: String,
    /// Description.
    pub description: String,
    /// Estimated financial impact in USD (if quantifiable).
    pub estimated_impact_usd: Option<u64>,
}

/// A security event published to the bus.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SecurityEvent {
    VulnDiscovered(Finding),
    ExploitGenerated(ExploitBlueprint),
    DetectionTriggered(DetectionAlert),
    ThreatIntelUpdate(ThreatIndicator),
    AptPhaseAdvanced { group: String, phase: String },
    BlockchainAnomaly(BlockchainAlert),
    ExtensionProposed { module_name: String, description: String },
    PentestPhaseComplete { phase: String, findings_count: usize },
}

impl SecurityEvent {
    /// Return the `EventType` discriminant for this event.
    pub fn event_type(&self) -> EventType {
        match self {
            SecurityEvent::VulnDiscovered(_) => EventType::VulnDiscovered,
            SecurityEvent::ExploitGenerated(_) => EventType::ExploitGenerated,
            SecurityEvent::DetectionTriggered(_) => EventType::DetectionTriggered,
            SecurityEvent::ThreatIntelUpdate(_) => EventType::ThreatIntelUpdate,
            SecurityEvent::AptPhaseAdvanced { .. } => EventType::AptPhaseAdvanced,
            SecurityEvent::BlockchainAnomaly(_) => EventType::BlockchainAnomaly,
            SecurityEvent::ExtensionProposed { .. } => EventType::ExtensionProposed,
            SecurityEvent::PentestPhaseComplete { .. } => EventType::PentestPhaseComplete,
        }
    }
}

/// Capacity of each event type's broadcast channel.
const CHANNEL_CAPACITY: usize = 256;

/// Async event bus that routes security events between modules.
///
/// Uses a per-event-type broadcast channel so subscribers only receive
/// the event types they care about.
pub struct SecurityEventBus {
    senders: HashMap<EventType, broadcast::Sender<SecurityEvent>>,
}

impl SecurityEventBus {
    /// Create a new bus with channels for all event types.
    pub fn new() -> Self {
        let mut senders = HashMap::new();
        let event_types = [
            EventType::VulnDiscovered,
            EventType::ExploitGenerated,
            EventType::DetectionTriggered,
            EventType::ThreatIntelUpdate,
            EventType::AptPhaseAdvanced,
            EventType::BlockchainAnomaly,
            EventType::ExtensionProposed,
            EventType::PentestPhaseComplete,
        ];
        for event_type in event_types {
            let (tx, _) = broadcast::channel(CHANNEL_CAPACITY);
            senders.insert(event_type, tx);
        }
        Self { senders }
    }

    /// Subscribe to a specific event type. Returns a receiver that will get
    /// all future events of that type published to the bus.
    pub fn subscribe(&self, event_type: &EventType) -> Option<broadcast::Receiver<SecurityEvent>> {
        self.senders
            .get(event_type)
            .map(|tx| tx.subscribe())
    }

    /// Publish a security event. Returns the number of active subscribers that
    /// received the event, or an error if the channel is full or no sender exists.
    pub fn publish(&self, event: SecurityEvent) -> anyhow::Result<usize> {
        let event_type = event.event_type();
        let sender = self.senders.get(&event_type).ok_or_else(|| {
            anyhow::anyhow!("No channel registered for event type {:?}", event_type)
        })?;
        let count = sender.send(event).unwrap_or(0);
        Ok(count)
    }

    /// Return the number of active receivers for the given event type.
    pub fn subscriber_count(&self, event_type: &EventType) -> usize {
        self.senders
            .get(event_type)
            .map(|tx| tx.receiver_count())
            .unwrap_or(0)
    }
}

impl Default for SecurityEventBus {
    fn default() -> Self {
        Self::new()
    }
}

/// Convenience wiring: when a vulnerability is discovered, publish to the bus
/// so that the blue team can check detection coverage.
pub fn wire_vuln_to_blue_team(bus: &SecurityEventBus, finding: Finding) -> anyhow::Result<()> {
    bus.publish(SecurityEvent::VulnDiscovered(finding))?;
    Ok(())
}

/// Convenience wiring: when an exploit is generated, publish to the bus so
/// that the pentest engine can incorporate it.
pub fn wire_exploit_to_pentest(
    bus: &SecurityEventBus,
    blueprint: ExploitBlueprint,
) -> anyhow::Result<()> {
    bus.publish(SecurityEvent::ExploitGenerated(blueprint))?;
    Ok(())
}

/// Convenience wiring: when a blockchain vulnerability is found, propose a new
/// meta-agent skill for it.
pub fn wire_blockchain_to_meta(
    bus: &SecurityEventBus,
    alert: BlockchainAlert,
) -> anyhow::Result<()> {
    let module_name = format!("blockchain-{}", alert.anomaly_type.replace(' ', "-"));
    bus.publish(SecurityEvent::BlockchainAnomaly(alert.clone()))?;
    bus.publish(SecurityEvent::ExtensionProposed {
        module_name,
        description: format!(
            "Auto-generated skill for blockchain anomaly: {}",
            alert.description
        ),
    })?;
    Ok(())
}
